### ISSUE TITLE
'npm test' fails

### ISSUE THREAD

**Issue by cybre-finn** [fdiogo/bityn#22]
I always get this when trying to run the tests (even when using an untouched version):

```
> bityn@1.0.0 test /home/xx/Sync/Coding/Hacktoberfest/test/bityn
> npm run lint && mocha --timeout 0 --reporter nyan test/


> bityn@1.0.0 lint /home/xx/Sync/Coding/Hacktoberfest/test/bityn
> eslint app.js lib test

/home/xx/Sync/Coding/Hacktoberfest/test/bityn/test/models.spec.js:2
const {expect} = require('chai');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/xx/Sync/Coding/Hacktoberfest/test/bityn/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/xx/Sync/Coding/Hacktoberfest/test/bityn/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/xx/Sync/Coding/Hacktoberfest/test/bityn/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/xx/Sync/Coding/Hacktoberfest/test/bityn/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.
```

**Comment by fdiogo** [comment]
what does 'node --version' give you?

**Comment by cybre-finn** [comment]
@fdiogo v4.6.1

**Comment by fdiogo** [comment]
Yeah you need to update it xD node is now at v6.9.1. You can either go [here](https://nodejs.org/en/) and do it manually or use the nvm (node version manager)

**Comment by cybre-finn** [comment]
Tests are passing now. \o/
Thanks!
